[package]
name = "soroban-animals"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "0.4.0"   # Tercihen en güncel sürümü kullanın
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.17.0"
